name: node-api-stage-codedeploy

on:
  workflow_dispatch:
    inputs:
      codedeploy_rollback:
        description: 'Trigger rollback in dependent workflow if value if True'
        required: false
      distinct_id:
        description: "This input required to run the workflow from return-dispatch"

permissions:
  id-token: write 
  contents: read
  pull-requests: write
  security-events: write
  actions: read

jobs:
  codedeploy:
    name: Trigger codedeploy with latest commit to Stage
    runs-on: ubuntu-latest

    environment:
      name: STAGE

    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - name: Set env codedeploy_rollback
        run: echo "codedeploy_rollback=${{ inputs.codedeploy_rollback }}" >> $GITHUB_ENV

      - name: Print codedeploy_rollback env
        run: echo "Rollback env is ${{ inputs.codedeploy_rollback }}"

      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}