name: node-api-stage-codedeploy

on:
  workflow_dispatch:
    inputs:
      codedeploy_rollback:
        description: 'Trigger rollback in dependent workflow if value if True'
        required: false
      environment:
        description: 'Environment to deploy'
        required: true
        type: string
      distinct_id:
        description: "This input required to run the workflow from return-dispatch"

permissions:
  id-token: write 
  contents: read
  pull-requests: write
  security-events: write
  actions: read

jobs:
  codedeploy:
    name: Trigger codedeploy with latest commit to Stage
    runs-on: ubuntu-latest

    environment:
      name: STAGE

    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - name: Print inputs
        run: |
          echo "Codedeploy rollback  is : ${{ inputs.codedeploy_rollback }}"
          echo "Environment is : ${{ inputs.environment }}"

      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}