name: release-public-web-version
on:
  workflow_dispatch:
    inputs:
      distinct_id:
        description: "This input required to run the workflow from return-dispatch"

jobs:
  publish_codedeploy_dev:
    if: github.ref == 'refs/heads/multi_tenant_dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: multi_tenant_dev

      - name: Echo Branch name
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo $branch_name

      - name: run codedeploy-dev workflow
        env:
          GITHUB_TOKEN:  ${{ secrets.GH_TOKEN }}
        run: |
          gh workflow run codedeploy-dev.yml \
          --ref=multi_tenant_dev \
          --repo prashant-cloudbolt/workflow-target1

      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}

  publish_codedeploy_stage:
    if: github.ref == 'refs/heads/multi_tenant_stage'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: multi_tenant_stage

      - name: Echo Branch name
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo $branch_name

      - name: run codedeploy-stage workflow
        env:
          GITHUB_TOKEN:  ${{ secrets.GH_TOKEN }}
        run: |
          gh workflow run codedeploy-mirastage.yml \
          --ref=multi_tenant_stage \
          --repo prashant-cloudbolt/workflow-target1

      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}